/* Generated by AN DISI Unibo */ 
package it.unibo.firefly_3

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly_3 ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		   
			   var  X          = 0
			   var  Y          = 2
			   var Timer       = java.util.Random().nextLong(1000L,2000L ) 
			
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | X=$X Y=$Y  Timer=$Timer")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="flash", cond=doswitch() )
				}	 
				state("flash") { //this:State
					action { //it:State
						forward("cellstate", "cellstate($X,$Y,1)" ,"griddisplay" ) 
						delay(500) 
						forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_flash", 
				 	 					  scope, context!!, "local_tout_"+name+"_flash", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t04",targetState="flash",cond=whenTimeout("local_tout_"+name+"_flash"))   
					transition(edgeName="t05",targetState="handlecoordinate",cond=whenDispatch("sync"))
				}	 
				state("handlecoordinate") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sync(T)"), Term.createTerm("coordinate(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val Vasstring = payloadArg(0)
												val V = Vasstring.toLong()
												Timer = V
								CommUtils.outgreen("new timer $V")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="flash", cond=doswitch() )
				}	 
			}
		}
} 
