/* Generated by AN DISI Unibo */ 
package it.unibo.orchestrator

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Orchestrator ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "setup"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
		       val SOGLIA = 50 
		       var isSynced = false
		return { //this:ActionBasciFsm
				state("setup") { //this:State
					action { //it:State
						 clearlog("./logs/app_firefly.log")  
						createActorDynamically("firefly", "_1", false)
						createActorDynamically("firefly", "_2", false)
						createActorDynamically("firefly", "_3", false)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="evaluate",cond=whenEvent("sonarinput"))
				}	 
				state("evaluate") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("range(V)"), Term.createTerm("range(V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val dist = payloadArg(0).toInt()  
								if(  dist < SOGLIA && !isSynced  
								 ){CommUtils.outred("$name | Distanza $dist < $SOGLIA. Avvio SYNC")
								 isSynced = true  
								emit("dosync", "dosync(1000)" ) 
								}
								if(  dist >= SOGLIA && isSynced  
								 ){CommUtils.outgreen("$name | Distanza $dist >= $SOGLIA. Interrompo SYNC")
								 isSynced = false  
								emit("cancelsync", "cancelsync(ok)" ) 
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
