/* Generated by AN DISI Unibo */ 
package it.unibo.firefly

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
		       var row = 0
		       var col = 0
		       var period = 500L
		       
		       fun initCoords() { 
		              val idx = name.replace("firefly_","") 
		              col = idx.toInt() 
		       }
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 initCoords()  
						 period = java.util.Random().nextLong(500L, 2000L)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="lightOn", cond=doswitch() )
				}	 
				state("lightOn") { //this:State
					action { //it:State
						forward("cellstatus", "cellstatus($X,$Y,1)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_lightOn", 
				 	 					  scope, context!!, "local_tout_"+name+"_lightOn", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t11",targetState="lightOff",cond=whenTimeout("local_tout_"+name+"_lightOn"))   
					transition(edgeName="t12",targetState="onSync",cond=whenEvent("dosync"))
					transition(edgeName="t13",targetState="onUnsync",cond=whenEvent("cancelsync"))
				}	 
				state("lightOff") { //this:State
					action { //it:State
						forward("cellstatus", "cellstatus($X,$Y,0)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_lightOff", 
				 	 					  scope, context!!, "local_tout_"+name+"_lightOff", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t24",targetState="lightOn",cond=whenTimeout("local_tout_"+name+"_lightOff"))   
					transition(edgeName="t25",targetState="onSync",cond=whenEvent("dosync"))
					transition(edgeName="t26",targetState="onUnsync",cond=whenEvent("cancelsync"))
				}	 
				state("onSync") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("dosync(PERIOD)"), Term.createTerm("dosync(P)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								               val newP = payloadArg(0).toLong()
								               period = newP
								CommUtils.outgreen("$name | Frequenza fissa ricevuta: $newP")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="lightOn", cond=doswitch() )
				}	 
				state("onUnsync") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | Sincronizzazione disattivata")
						 period = java.util.Random().nextLong(500L, 2000L)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="lightOn", cond=doswitch() )
				}	 
			}
		}
} 
